#
# detect packages which failed because of processes are running inside chroot
#
EXPLAIN='due to leaving processes running behind'
PRIORITY=250
PATTERN='ERROR: FAIL: Processes are running inside chroot'
WHERE='fail bugged affected'
ISSUE=0
HEADER='Packages with failed logs because of processes left behind'
HELPTEXT='
<p>
There were processes running inside the chroot at the end of the piuparts run.
This is probably due to directly calling /etc/rc.d/ scripts in packages maintainer scripts, which is a violation of policy 9.3.3.2 and must be replaced by using invoke-rc.d (which will respect an optionally existing policy-rc.d) - see
<a href="http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3" target="_blank">http://www.debian.org/doc/debian-policy/ch-opersys.html#s9.3.3</a>, /usr/share/doc/sysv-rc/README.invoke-rc.d.gz and /usr/share/doc/sysv-rc/README.policy-rc.d.gz.
</p>
<p>
According to the thread started at <a href="http://lists.debian.org/debian-devel/2009/08/msg00182.html" target="_blank">200908061127.35727.holger@layer-acht.org</a> these bugs are to be filed with severity <b>serious</b>.
</p>
'
